export const SECTOR_DATA_FETCHED = 'SECTOR_DATA_FETCHED';
export const SECTOR_MAP_FETCHED = 'SECTOR_MAP_FETCHED';
export const SEAT_SELECTED = 'SEAT_SELECTED';
export const SEAT_UNSELECTED = 'SEAT_UNSELECTED';
export const RESERVATION_COMPLETED = 'RESERVATION_COMPLETED';